# Generated by Django 2.0.7 on 2018-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20180723_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_followers_+', to='post.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followings',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_followings_+', to='post.UserProfile'),
        ),
    ]
