# Generated by Django 2.0.7 on 2018-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_userprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_followers_+', to='post.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_followings_+', to='post.UserProfile'),
        ),
    ]
