# Generated by Django 2.0.7 on 2018-07-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20180724_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followings',
            new_name='follows',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
    ]
